target 'Lottie-Example-Swift' do
  use_frameworks!

  pod 'lottie-ios', :path => '../'
  
  target 'Lottie-Example-SwiftTests' do
    inherit! :search_paths
  end

  target 'Lottie-Example-SwiftUITests' do
    inherit! :search_paths
  end

end
